name: "Build on Pull Request"

on:
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
      - run: rm -rf /tmp/gobuild*
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          args: build --snapshot --skip before
